### PR TITLE
buffer/cursor: Handle EOF in ExtractCursor without crashing, add tests

### PR DESCRIPTION
**Pull request by dtcaciuc**

### CODE REVIEW

**Comment by dtcaciuc** [comment]
Bah, wrong method name in description.

**Comment by kisielk** [comment]
Thanks. That fixes the bug at least. I'm wondering if whenever we insert a `\n` we should also subtract from n.

**Comment by dtcaciuc** [comment]
Good question. Right now it does. You get back a single array of bytes so if we allow extraction across lines, newline characters have to be there. Since newlines are characters like every other, to retain the "request N bytes, get N bytes" behaviour, it should in fact subtract from n.

**Comment by kisielk** [comment]
Oh, it does right now. For some reason when I read the code, it seemed like it didn't.

**Pull request merged**
